version: "3"
services:
  mysql:
    container_name: mysql
    build: ./docker/mysql
    image: javatest/mysql:1.0
    command: 
      - mysql < /mysql/sakila-schema.sql
      - mysql < /mysql/sakila-data.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  java-1:
    container_name: mysql
    build: ./docker/java
    image: javatest/java:1.0
    links:
      - mysql
    environment:
      MYSQL_IP: mysql
      MYSQL_PORT: 3306      